/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BingoQuizGame;

import java.util.Random;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author aslam
 */

public class BingoView extends javax.swing.JFrame {

    /**
     * Creates new form BingoView
     */
    public BingoView() {
        initComponents();
    }
    
    //bikin getter untuk semua button biar bisa diakses di BingoController
    public JButton getBtnStartGame() {
        return btnStartGame;
    }
    public JButton getbtnTryAgain() {
        return btnTryAgain;
    }
    public JButton getBtnEndGame() {
        return btnEndGame;
    }
    public JButton getBtnBack() {
        return btnBack;
    }
    public JPanel getBoard() {
        return board;
    }
    
    public JTextField getwin2Field() {
        return win2field;
    }
    public JTextField getwin1Field() {
        return win1field;
    }
    public JTextField getroundCountField() {
        return roundCountField;
    }
    public JTextArea getGameLogArea() {
        return GameLogArea;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        win2field1 = new javax.swing.JTextField();
        BingoPanel = new javax.swing.JPanel();
        board = new javax.swing.JPanel();
        tiles16 = new javax.swing.JButton();
        tiles17 = new javax.swing.JButton();
        tiles18 = new javax.swing.JButton();
        tiles19 = new javax.swing.JButton();
        tiles20 = new javax.swing.JButton();
        tiles21 = new javax.swing.JButton();
        tiles22 = new javax.swing.JButton();
        tiles23 = new javax.swing.JButton();
        tiles24 = new javax.swing.JButton();
        tiles25 = new javax.swing.JButton();
        tiles1 = new javax.swing.JButton();
        tiles2 = new javax.swing.JButton();
        tiles3 = new javax.swing.JButton();
        tiles4 = new javax.swing.JButton();
        tiles5 = new javax.swing.JButton();
        tiles6 = new javax.swing.JButton();
        tiles7 = new javax.swing.JButton();
        tiles8 = new javax.swing.JButton();
        tiles9 = new javax.swing.JButton();
        tiles10 = new javax.swing.JButton();
        tiles11 = new javax.swing.JButton();
        tiles12 = new javax.swing.JButton();
        tiles13 = new javax.swing.JButton();
        tiles14 = new javax.swing.JButton();
        tiles15 = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        btnTryAgain = new javax.swing.JButton();
        btnEndGame = new javax.swing.JButton();
        player1Panel = new javax.swing.JPanel();
        LabelPlayer1 = new javax.swing.JLabel();
        winCount1 = new javax.swing.JLabel();
        win1field = new javax.swing.JTextField();
        player2Panel1 = new javax.swing.JPanel();
        LabelPlayer2 = new javax.swing.JLabel();
        winCount3 = new javax.swing.JLabel();
        win2field = new javax.swing.JTextField();
        roundCountField = new javax.swing.JTextField();
        RoundLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        GameLogArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BingoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BingoPanel.setPreferredSize(new java.awt.Dimension(650, 400));

        board.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        board.setPreferredSize(new java.awt.Dimension(250, 250));
        board.setLayout(new java.awt.GridLayout(5, 5));
        board.add(tiles16);
        board.add(tiles17);
        board.add(tiles18);
        board.add(tiles19);

        tiles20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles20ActionPerformed(evt);
            }
        });
        board.add(tiles20);
        board.add(tiles21);
        board.add(tiles22);
        board.add(tiles23);

        tiles24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles24ActionPerformed(evt);
            }
        });
        board.add(tiles24);

        tiles25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles25ActionPerformed(evt);
            }
        });
        board.add(tiles25);

        tiles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles1ActionPerformed(evt);
            }
        });
        board.add(tiles1);

        tiles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles2ActionPerformed(evt);
            }
        });
        board.add(tiles2);
        board.add(tiles3);
        board.add(tiles4);

        tiles5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles5ActionPerformed(evt);
            }
        });
        board.add(tiles5);
        board.add(tiles6);
        board.add(tiles7);
        board.add(tiles8);
        board.add(tiles9);
        board.add(tiles10);
        board.add(tiles11);
        board.add(tiles12);

        tiles13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles13ActionPerformed(evt);
            }
        });
        board.add(tiles13);
        board.add(tiles14);
        board.add(tiles15);

        btnStartGame.setText("Start Game");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        btnTryAgain.setText("Try Again");
        btnTryAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryAgainActionPerformed(evt);
            }
        });

        btnEndGame.setText("End Game");

        player1Panel.setBackground(new java.awt.Color(204, 204, 204));
        player1Panel.setPreferredSize(new java.awt.Dimension(175, 75));

        LabelPlayer1.setText("Player 1");

        winCount1.setText("Win =");

        javax.swing.GroupLayout player1PanelLayout = new javax.swing.GroupLayout(player1Panel);
        player1Panel.setLayout(player1PanelLayout);
        player1PanelLayout.setHorizontalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1PanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player1PanelLayout.createSequentialGroup()
                        .addComponent(winCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(win1field, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        player1PanelLayout.setVerticalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPlayer1)
                .addGap(18, 18, 18)
                .addGroup(player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winCount1)
                    .addComponent(win1field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        player2Panel1.setBackground(new java.awt.Color(204, 204, 204));
        player2Panel1.setForeground(new java.awt.Color(255, 255, 255));
        player2Panel1.setPreferredSize(new java.awt.Dimension(175, 75));

        LabelPlayer2.setText("Player 2");

        winCount3.setText("Win =");

        win2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                win2fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout player2Panel1Layout = new javax.swing.GroupLayout(player2Panel1);
        player2Panel1.setLayout(player2Panel1Layout);
        player2Panel1Layout.setHorizontalGroup(
            player2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player2Panel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(winCount3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(win2field, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        player2Panel1Layout.setVerticalGroup(
            player2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(player2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winCount3)
                    .addComponent(win2field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        roundCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundCountFieldActionPerformed(evt);
            }
        });

        RoundLabel.setText("Round");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        GameLogArea.setColumns(20);
        GameLogArea.setRows(5);
        jScrollPane1.setViewportView(GameLogArea);

        javax.swing.GroupLayout BingoPanelLayout = new javax.swing.GroupLayout(BingoPanel);
        BingoPanel.setLayout(BingoPanelLayout);
        BingoPanelLayout.setHorizontalGroup(
            BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BingoPanelLayout.createSequentialGroup()
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BingoPanelLayout.createSequentialGroup()
                                .addComponent(RoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(roundCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BingoPanelLayout.createSequentialGroup()
                                .addComponent(btnStartGame)
                                .addGap(30, 30, 30)
                                .addComponent(btnTryAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnEndGame)
                                .addGap(27, 27, 27)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player2Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(player1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        BingoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, player1Panel, player2Panel1});

        BingoPanelLayout.setVerticalGroup(
            BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BingoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEndGame)
                    .addComponent(btnTryAgain)
                    .addComponent(btnStartGame)
                    .addComponent(btnBack))
                .addGap(26, 26, 26)
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roundCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoundLabel))
                        .addGap(41, 41, 41)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(player2Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        BingoPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {player1Panel, player2Panel1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BingoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BingoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void btnTryAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryAgainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTryAgainActionPerformed

    private void tiles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles1ActionPerformed

    private void tiles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles2ActionPerformed

    private void tiles5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles5ActionPerformed

    private void win2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_win2fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_win2fieldActionPerformed

    private void roundCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundCountFieldActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void tiles20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles20ActionPerformed

    private void tiles24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles24ActionPerformed

    private void tiles25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles25ActionPerformed

    private void tiles13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles13ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                BingoModel model = new BingoModel();
//                BingoView view = new BingoView();
//                BingoController controller = new BingoController(model, view);
//                view.setVisible(true);
//                new BingoView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BingoPanel;
    private javax.swing.JTextArea GameLogArea;
    private javax.swing.JLabel LabelPlayer1;
    private javax.swing.JLabel LabelPlayer2;
    private javax.swing.JLabel RoundLabel;
    private javax.swing.JPanel board;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEndGame;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JButton btnTryAgain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel player1Panel;
    private javax.swing.JPanel player2Panel1;
    private javax.swing.JTextField roundCountField;
    private javax.swing.JButton tiles1;
    private javax.swing.JButton tiles10;
    private javax.swing.JButton tiles11;
    private javax.swing.JButton tiles12;
    private javax.swing.JButton tiles13;
    private javax.swing.JButton tiles14;
    private javax.swing.JButton tiles15;
    private javax.swing.JButton tiles16;
    private javax.swing.JButton tiles17;
    private javax.swing.JButton tiles18;
    private javax.swing.JButton tiles19;
    private javax.swing.JButton tiles2;
    private javax.swing.JButton tiles20;
    private javax.swing.JButton tiles21;
    private javax.swing.JButton tiles22;
    private javax.swing.JButton tiles23;
    private javax.swing.JButton tiles24;
    private javax.swing.JButton tiles25;
    private javax.swing.JButton tiles3;
    private javax.swing.JButton tiles4;
    private javax.swing.JButton tiles5;
    private javax.swing.JButton tiles6;
    private javax.swing.JButton tiles7;
    private javax.swing.JButton tiles8;
    private javax.swing.JButton tiles9;
    private javax.swing.JTextField win1field;
    private javax.swing.JTextField win2field;
    private javax.swing.JTextField win2field1;
    private javax.swing.JLabel winCount1;
    private javax.swing.JLabel winCount3;
    // End of variables declaration//GEN-END:variables
}