/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bingo.game.quiz;

import java.util.Random;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author aslam
 */

public class BingoView extends javax.swing.JFrame {

    /**
     * Creates new form BingoView
     */
    public BingoView() {
        initComponents();
    }
    
    //bikin getter untuk semua button biar bisa diakses di BingoController
    public JButton getBtnStartGame() {
        return btnStartGame;
    }
    public JButton getbtnTryAgain() {
        return btnTryAgain;
    }
    public JButton getBtnEndGame() {
        return btnEndGame;
    }
    public JPanel getBoard() {
        return board;
    }
    
    public JTextField getwin2Field() {
        return win2field;
    }
    public JTextField getwin1Field() {
        return win1field;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        win2field1 = new javax.swing.JTextField();
        BingoPanel = new javax.swing.JPanel();
        board = new javax.swing.JPanel();
        tiles1 = new javax.swing.JButton();
        tiles2 = new javax.swing.JButton();
        tiles3 = new javax.swing.JButton();
        tiles4 = new javax.swing.JButton();
        tiles5 = new javax.swing.JButton();
        tiles6 = new javax.swing.JButton();
        tiles7 = new javax.swing.JButton();
        tiles8 = new javax.swing.JButton();
        tiles9 = new javax.swing.JButton();
        tiles10 = new javax.swing.JButton();
        tiles11 = new javax.swing.JButton();
        tiles12 = new javax.swing.JButton();
        tiles13 = new javax.swing.JButton();
        tiles14 = new javax.swing.JButton();
        tiles15 = new javax.swing.JButton();
        tiles16 = new javax.swing.JButton();
        tiles17 = new javax.swing.JButton();
        tiles18 = new javax.swing.JButton();
        tiles19 = new javax.swing.JButton();
        tiles20 = new javax.swing.JButton();
        tiles21 = new javax.swing.JButton();
        tiles22 = new javax.swing.JButton();
        tiles23 = new javax.swing.JButton();
        tiles24 = new javax.swing.JButton();
        tiles25 = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        btnTryAgain = new javax.swing.JButton();
        btnEndGame = new javax.swing.JButton();
        player1Panel = new javax.swing.JPanel();
        LabelPlayer2 = new javax.swing.JLabel();
        LabelPlayer1 = new javax.swing.JLabel();
        player2Panel1 = new javax.swing.JPanel();
        winCount1 = new javax.swing.JLabel();
        winCount3 = new javax.swing.JLabel();
        roundCount = new javax.swing.JTextField();
        RoundLabel = new javax.swing.JLabel();
        win2field = new javax.swing.JTextField();
        win1field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BingoPanel.setPreferredSize(new java.awt.Dimension(650, 400));

        board.setPreferredSize(new java.awt.Dimension(250, 250));
        board.setLayout(new java.awt.GridLayout(5, 5));

        tiles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles1ActionPerformed(evt);
            }
        });
        board.add(tiles1);

        tiles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles2ActionPerformed(evt);
            }
        });
        board.add(tiles2);
        board.add(tiles3);
        board.add(tiles4);

        tiles5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiles5ActionPerformed(evt);
            }
        });
        board.add(tiles5);
        board.add(tiles6);
        board.add(tiles7);
        board.add(tiles8);
        board.add(tiles9);
        board.add(tiles10);
        board.add(tiles11);
        board.add(tiles12);
        board.add(tiles13);
        board.add(tiles14);
        board.add(tiles15);
        board.add(tiles16);
        board.add(tiles17);
        board.add(tiles18);
        board.add(tiles19);
        board.add(tiles20);
        board.add(tiles21);
        board.add(tiles22);
        board.add(tiles23);
        board.add(tiles24);
        board.add(tiles25);

        btnStartGame.setText("Start Game");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        btnTryAgain.setText("Try Again");
        btnTryAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryAgainActionPerformed(evt);
            }
        });

        btnEndGame.setText("End Game");

        player1Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout player1PanelLayout = new javax.swing.GroupLayout(player1Panel);
        player1Panel.setLayout(player1PanelLayout);
        player1PanelLayout.setHorizontalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        player1PanelLayout.setVerticalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        LabelPlayer2.setText("Player 2");

        LabelPlayer1.setText("Player 1");

        player2Panel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout player2Panel1Layout = new javax.swing.GroupLayout(player2Panel1);
        player2Panel1.setLayout(player2Panel1Layout);
        player2Panel1Layout.setHorizontalGroup(
            player2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        player2Panel1Layout.setVerticalGroup(
            player2Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        winCount1.setText("Win =");

        winCount3.setText("Win =");

        RoundLabel.setText("Round");

        win2field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                win2fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BingoPanelLayout = new javax.swing.GroupLayout(BingoPanel);
        BingoPanel.setLayout(BingoPanelLayout);
        BingoPanelLayout.setHorizontalGroup(
            BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BingoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BingoPanelLayout.createSequentialGroup()
                                .addComponent(winCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(win1field, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(RoundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnStartGame))
                        .addGap(30, 30, 30)
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BingoPanelLayout.createSequentialGroup()
                                .addComponent(btnTryAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnEndGame)))
                        .addGap(113, 113, 113))
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BingoPanelLayout.createSequentialGroup()
                                .addComponent(player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BingoPanelLayout.createSequentialGroup()
                                .addComponent(LabelPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(BingoPanelLayout.createSequentialGroup()
                                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(player2Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(BingoPanelLayout.createSequentialGroup()
                                        .addComponent(winCount3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(win2field, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        BingoPanelLayout.setVerticalGroup(
            BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BingoPanelLayout.createSequentialGroup()
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEndGame)
                            .addComponent(btnTryAgain)
                            .addComponent(btnStartGame))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roundCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoundLabel))
                        .addGap(18, 18, 18))
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPlayer2)
                            .addComponent(LabelPlayer1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(winCount1)
                                .addComponent(win1field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(winCount3)
                                .addComponent(win2field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BingoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BingoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void btnTryAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryAgainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTryAgainActionPerformed

    private void tiles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles1ActionPerformed

    private void tiles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles2ActionPerformed

    private void tiles5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiles5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiles5ActionPerformed

    private void win2fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_win2fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_win2fieldActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                BingoModel model = new BingoModel();
//                BingoView view = new BingoView();
//                BingoController controller = new BingoController(model, view);
//                view.setVisible(true);
//                new BingoView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BingoPanel;
    private javax.swing.JLabel LabelPlayer1;
    private javax.swing.JLabel LabelPlayer2;
    private javax.swing.JLabel RoundLabel;
    private javax.swing.JPanel board;
    private javax.swing.JButton btnEndGame;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JButton btnTryAgain;
    private javax.swing.JPanel player1Panel;
    private javax.swing.JPanel player2Panel1;
    private javax.swing.JTextField roundCount;
    private javax.swing.JButton tiles1;
    private javax.swing.JButton tiles10;
    private javax.swing.JButton tiles11;
    private javax.swing.JButton tiles12;
    private javax.swing.JButton tiles13;
    private javax.swing.JButton tiles14;
    private javax.swing.JButton tiles15;
    private javax.swing.JButton tiles16;
    private javax.swing.JButton tiles17;
    private javax.swing.JButton tiles18;
    private javax.swing.JButton tiles19;
    private javax.swing.JButton tiles2;
    private javax.swing.JButton tiles20;
    private javax.swing.JButton tiles21;
    private javax.swing.JButton tiles22;
    private javax.swing.JButton tiles23;
    private javax.swing.JButton tiles24;
    private javax.swing.JButton tiles25;
    private javax.swing.JButton tiles3;
    private javax.swing.JButton tiles4;
    private javax.swing.JButton tiles5;
    private javax.swing.JButton tiles6;
    private javax.swing.JButton tiles7;
    private javax.swing.JButton tiles8;
    private javax.swing.JButton tiles9;
    private javax.swing.JTextField win1field;
    private javax.swing.JTextField win2field;
    private javax.swing.JTextField win2field1;
    private javax.swing.JLabel winCount1;
    private javax.swing.JLabel winCount3;
    // End of variables declaration//GEN-END:variables
}