/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bingo.game.quiz;

import java.util.Random;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author aslam
 */

public class BingoView extends javax.swing.JFrame {

    /**
     * Creates new form BingoView
     */
    public BingoView() {
        initComponents();
    }
    
    //bikin getter untuk semua button biar bisa diakses di BingoController
    public JButton getBtnStartGame() {
        return btnStartGame;
    }
    public JButton getBtnGenerateQuiz() {
        return btnGenerateQuiz;
    }
    public JButton getBtnEndGame() {
        return btnEndGame;
    }
    public JPanel getBoard() {
        return board;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BingoPanel = new javax.swing.JPanel();
        board = new javax.swing.JPanel();
        tiles1 = new javax.swing.JButton();
        tiles2 = new javax.swing.JButton();
        tiles3 = new javax.swing.JButton();
        tiles4 = new javax.swing.JButton();
        tiles5 = new javax.swing.JButton();
        tiles6 = new javax.swing.JButton();
        tiles7 = new javax.swing.JButton();
        tiles8 = new javax.swing.JButton();
        tiles9 = new javax.swing.JButton();
        tiles10 = new javax.swing.JButton();
        tiles11 = new javax.swing.JButton();
        tiles12 = new javax.swing.JButton();
        tiles13 = new javax.swing.JButton();
        tiles14 = new javax.swing.JButton();
        tiles15 = new javax.swing.JButton();
        tiles16 = new javax.swing.JButton();
        tiles17 = new javax.swing.JButton();
        tiles18 = new javax.swing.JButton();
        tiles19 = new javax.swing.JButton();
        tiles20 = new javax.swing.JButton();
        tiles21 = new javax.swing.JButton();
        tiles22 = new javax.swing.JButton();
        tiles23 = new javax.swing.JButton();
        tiles24 = new javax.swing.JButton();
        tiles25 = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        btnGenerateQuiz = new javax.swing.JButton();
        btnEndGame = new javax.swing.JButton();
        player2Panel = new javax.swing.JPanel();
        player1Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BingoPanel.setPreferredSize(new java.awt.Dimension(650, 400));

        board.setPreferredSize(new java.awt.Dimension(250, 250));
        board.setLayout(new java.awt.GridLayout(5, 5));
        board.add(tiles1);
        board.add(tiles2);
        board.add(tiles3);
        board.add(tiles4);
        board.add(tiles5);
        board.add(tiles6);
        board.add(tiles7);
        board.add(tiles8);
        board.add(tiles9);
        board.add(tiles10);
        board.add(tiles11);
        board.add(tiles12);
        board.add(tiles13);
        board.add(tiles14);
        board.add(tiles15);
        board.add(tiles16);
        board.add(tiles17);
        board.add(tiles18);
        board.add(tiles19);
        board.add(tiles20);
        board.add(tiles21);
        board.add(tiles22);
        board.add(tiles23);
        board.add(tiles24);
        board.add(tiles25);

        btnStartGame.setText("Start Game");
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });

        btnGenerateQuiz.setText("Generate Quiz");

        btnEndGame.setText("End Game");

        player2Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout player2PanelLayout = new javax.swing.GroupLayout(player2Panel);
        player2Panel.setLayout(player2PanelLayout);
        player2PanelLayout.setHorizontalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        player2PanelLayout.setVerticalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        player1Panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout player1PanelLayout = new javax.swing.GroupLayout(player1Panel);
        player1Panel.setLayout(player1PanelLayout);
        player1PanelLayout.setHorizontalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        player1PanelLayout.setVerticalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BingoPanelLayout = new javax.swing.GroupLayout(BingoPanel);
        BingoPanel.setLayout(BingoPanelLayout);
        BingoPanelLayout.setHorizontalGroup(
            BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BingoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addComponent(player1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGap(0, 128, Short.MAX_VALUE)
                        .addComponent(btnStartGame)
                        .addGap(34, 34, 34)
                        .addComponent(btnGenerateQuiz)
                        .addGap(33, 33, 33)
                        .addComponent(btnEndGame)
                        .addGap(141, 141, 141))))
        );
        BingoPanelLayout.setVerticalGroup(
            BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BingoPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEndGame)
                    .addComponent(btnGenerateQuiz)
                    .addComponent(btnStartGame))
                .addGap(10, 10, 10)
                .addGroup(BingoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(board, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(player1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BingoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BingoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BingoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartGameActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(BingoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                BingoModel model = new BingoModel();
//                BingoView view = new BingoView();
//                BingoController controller = new BingoController(model, view);
//                view.setVisible(true);
//                new BingoView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BingoPanel;
    private javax.swing.JPanel board;
    private javax.swing.JButton btnEndGame;
    private javax.swing.JButton btnGenerateQuiz;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JPanel player1Panel;
    private javax.swing.JPanel player2Panel;
    private javax.swing.JButton tiles1;
    private javax.swing.JButton tiles10;
    private javax.swing.JButton tiles11;
    private javax.swing.JButton tiles12;
    private javax.swing.JButton tiles13;
    private javax.swing.JButton tiles14;
    private javax.swing.JButton tiles15;
    private javax.swing.JButton tiles16;
    private javax.swing.JButton tiles17;
    private javax.swing.JButton tiles18;
    private javax.swing.JButton tiles19;
    private javax.swing.JButton tiles2;
    private javax.swing.JButton tiles20;
    private javax.swing.JButton tiles21;
    private javax.swing.JButton tiles22;
    private javax.swing.JButton tiles23;
    private javax.swing.JButton tiles24;
    private javax.swing.JButton tiles25;
    private javax.swing.JButton tiles3;
    private javax.swing.JButton tiles4;
    private javax.swing.JButton tiles5;
    private javax.swing.JButton tiles6;
    private javax.swing.JButton tiles7;
    private javax.swing.JButton tiles8;
    private javax.swing.JButton tiles9;
    // End of variables declaration//GEN-END:variables
}
